/*
 * Copyright (C) IBM Corp. 2008.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.ibm.jaql.lang.expr.io;

import com.ibm.jaql.io.Adapter;
import com.ibm.jaql.json.type.JsonString;
import com.ibm.jaql.lang.core.Env;
import com.ibm.jaql.lang.expr.core.ConstExpr;
import com.ibm.jaql.lang.expr.core.Expr;
import com.ibm.jaql.lang.expr.core.MacroExpr;
import com.ibm.jaql.lang.expr.core.NameValueBinding;
import com.ibm.jaql.lang.expr.core.RecordExpr;
import com.ibm.jaql.lang.expr.function.DefaultBuiltInFunctionDescriptor;

/**
 * hbaseRead( tableExpr, {columns: columnExpr, lowKey:lowKeyExpr,
 * highKey:highKeyExpr, timestamp:timestampExpr}? )
 *  - string tableName <- evaluate tableExpr - JArray columns <- evaluate
 * columnExpr - string lowKey <- evaluate lowKeyExpr - string highKey <-
 * evaluate highKeyExpr - LongItem timestamp <- evaluate timestamp
 * 
 * Open a scanner on tableName, default column family and return an Iter that
 * wraps each hbase row in a JMap. Each tuple is generated by constructing one
 * or more ExprPairs. Each ExprPair p is generated by using the column name for
 * p.name and the value for p.value
 */
public class HBaseReadExpr extends MacroExpr
{
  public static class Descriptor extends DefaultBuiltInFunctionDescriptor.Par12
  {
    public Descriptor()
    {
      super("hbaseRead", HBaseReadExpr.class);
    }
  }
  
  /**
   * hbaseRead( string tableName, record args? ) )
   * 
   * @param exprs
   */
  public HBaseReadExpr(Expr[] exprs)
  {
    super(exprs);
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.ibm.jaql.lang.expr.core.MacroExpr#expand(com.ibm.jaql.lang.core.Env)
   */
  @Override
  public Expr expand(Env env) throws Exception
  {
    // replace the input with a record expression
    NameValueBinding tField = new NameValueBinding(Adapter.TYPE_NAME,
        new ConstExpr(new JsonString("hbase")));
    NameValueBinding lField = new NameValueBinding(Adapter.LOCATION_NAME,
        exprs[0]);
    RecordExpr rec = new RecordExpr(new Expr[]{tField, lField});
    NameValueBinding oField = new NameValueBinding(Adapter.INOPTIONS_NAME, exprs[1], false);
    rec.addChild(oField);
    return new ReadFn(rec);
  }
}
