/* Generated By:JavaCC: Do not edit this line. JsonParserConstants.java */
package com.ibm.jaql.json.parser;

public interface JsonParserConstants {

  int EOF = 0;
  int COLON = 5;
  int COMMA = 6;
  int DIGIT = 7;
  int LETTER = 8;
  int MAP_BEGIN = 9;
  int MAP_END = 10;
  int ARRAY_BEGIN = 11;
  int ARRAY_END = 12;
  int LPAREN = 13;
  int RPAREN = 14;
  int PLUS = 15;
  int LONG = 16;
  int REAL = 17;
  int DECIMAL = 18;
  int DOUBLE = 19;
  int TRUE = 20;
  int FALSE = 21;
  int NULL = 22;
  int ID = 23;
  int STRING1 = 26;
  int STRING2 = 27;
  int SINGLE_LINE_COMMENT = 46;

  int DEFAULT = 0;
  int IN_STRING1 = 1;
  int IN_STRING2 = 2;
  int WithinComment = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":\"",
    "\",\"",
    "<DIGIT>",
    "<LETTER>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "<LONG>",
    "<REAL>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<TRUE>",
    "<FALSE>",
    "<NULL>",
    "<ID>",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 29>",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\\\\\'\"",
    "\"\\\\\\\"\"",
    "\"\\\\\\\\\"",
    "\"\\\\/\"",
    "\"\\\\b\"",
    "\"\\\\f\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"\\\\t\"",
    "<token of kind 42>",
    "<token of kind 43>",
    "<token of kind 44>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 48>",
  };

}
