/* Generated By:JavaCC: Do not edit this line. JsonParserConstants.java */
package com.ibm.jaql.json.parser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JsonParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COLON = 5;
  /** RegularExpression Id. */
  int COMMA = 6;
  /** RegularExpression Id. */
  int DIGIT = 7;
  /** RegularExpression Id. */
  int LETTER = 8;
  /** RegularExpression Id. */
  int MAP_BEGIN = 9;
  /** RegularExpression Id. */
  int MAP_END = 10;
  /** RegularExpression Id. */
  int ARRAY_BEGIN = 11;
  /** RegularExpression Id. */
  int ARRAY_END = 12;
  /** RegularExpression Id. */
  int LPAREN = 13;
  /** RegularExpression Id. */
  int RPAREN = 14;
  /** RegularExpression Id. */
  int PLUS = 15;
  /** RegularExpression Id. */
  int LONG = 16;
  /** RegularExpression Id. */
  int REAL = 17;
  /** RegularExpression Id. */
  int DECIMAL = 18;
  /** RegularExpression Id. */
  int DOUBLE = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int NULL = 22;
  /** RegularExpression Id. */
  int ID = 23;
  /** RegularExpression Id. */
  int STRING1 = 26;
  /** RegularExpression Id. */
  int STRING2 = 27;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 46;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STRING1 = 1;
  /** Lexical state. */
  int IN_STRING2 = 2;
  /** Lexical state. */
  int WithinComment = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":\"",
    "\",\"",
    "<DIGIT>",
    "<LETTER>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "<LONG>",
    "<REAL>",
    "<DECIMAL>",
    "<DOUBLE>",
    "<TRUE>",
    "<FALSE>",
    "<NULL>",
    "<ID>",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\\\\\r\\n\"",
    "<token of kind 29>",
    "\"\\r\\n\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\\\\\\'\"",
    "\"\\\\\\\"\"",
    "\"\\\\\\\\\"",
    "\"\\\\/\"",
    "\"\\\\b\"",
    "\"\\\\f\"",
    "\"\\\\n\"",
    "\"\\\\r\"",
    "\"\\\\t\"",
    "<token of kind 42>",
    "<token of kind 43>",
    "<token of kind 44>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 48>",
  };

}
